package ru.tatiana.stacy.Entity;

import io.swagger.annotations.ApiModelProperty;

import javax.persistence.Entity;
import javax.persistence.Id;
import java.util.Date;

@Entity
public class ToDoList {
    @Id
    @ApiModelProperty(notes = "list_id (autogenerated) connected with to_do keytable")
    private int list_id;
    @ApiModelProperty(notes = "not-unique task's name")
    private String title;
    private String description;
    @ApiModelProperty(notes = "Date in format: yyyy-mm-dd")
    private Date date;
    @ApiModelProperty(notes = "Task's status: \n-1 - wait for start\n0 - in progress\n1 - have done")
    private int status;
    @ApiModelProperty(notes = "Priority: \n2 - high\n1 - middle\n0 - low")
    private int priority;
    @ApiModelProperty(notes = "Unique item_id (autogenerated)")
    private int item_id;

    public int getItem_id() {
        return item_id;
    }

    public void setItem_id(int item_id) {
        this.item_id = item_id;
    }

    public int getList_id() {
        return list_id;
    }

    public void setList_id(int list_id) {
        this.list_id = list_id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public int getPriority() {
        return priority;
    }

    public void setPriority(int priority) {
        this.priority = priority;
    }
}
