package ru.tatiana.stacy.Entity;

import io.swagger.annotations.ApiModelProperty;
import javax.persistence.*;
import java.math.BigDecimal;

public class Users {
    @ApiModelProperty(notes = "Unique users_id (autogenerated)")
    private int users_id;
    @ApiModelProperty(notes = "Unique user's name, choosing by user")
    private String name;
    @ApiModelProperty(notes = "Password to get access")
    private String password;
    public int getId() {
        return users_id;
    }

    public void setId(int users_id) {
        this.users_id = users_id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
}
